export const INCREMENT_ENTHUSIASM = "INCREMENT_ENTHUSIASM";
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const INCREMENT_ENTHUSIASM_BY = "INCREMENT_ENTHUSIASM_BY";
export type INCREMENT_ENTHUSIASM_BY = typeof INCREMENT_ENTHUSIASM_BY;

export const DECREMENT_ENTHUSIASM = "DECREMENT_ENTHUSIASM";
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const INCREMENT_ENTHUSIASM_ASYNC_START = "INCREMENT_ENTHUSIASM_ASYNC_START";
export type INCREMENT_ENTHUSIASM_ASYNC_START = typeof INCREMENT_ENTHUSIASM_ASYNC_START;

export const INCREMENT_ENTHUSIASM_ASYNC_SUCCESS = "INCREMENT_ENTHUSIASM_ASYNC_SUCCESS";
export type INCREMENT_ENTHUSIASM_ASYNC_SUCCESS = typeof INCREMENT_ENTHUSIASM_ASYNC_SUCCESS;
