export const START_SOCKET_SUBSCRIPTION = "START_SOCKET_SUBSCRIPTION";
export type START_SOCKET_SUBSCRIPTION = typeof START_SOCKET_SUBSCRIPTION;

export const STOP_SOCKET_SUBSCRIPTION = "STOP_SOCKET_SUBSCRIPTION";
export type STOP_SOCKET_SUBSCRIPTION = typeof STOP_SOCKET_SUBSCRIPTION;

export const CURRENCIES_REQUEST_START = "CURRENCIES_REQUEST_START";
export type CURRENCIES_REQUEST_START = typeof CURRENCIES_REQUEST_START;

export const CURRENCIES_REQUEST_CANCEL = "CURRENCIES_REQUEST_CANCEL";
export type CURRENCIES_REQUEST_CANCEL = typeof CURRENCIES_REQUEST_CANCEL;

export const CURRENCY_UPDATED = "CURRENCY_UPDATED";
export type CURRENCY_UPDATED = typeof CURRENCY_UPDATED;

