export const SUGGESTION_REQUESTED = "SUGGESTION_REQUESTED";
export type SUGGESTION_REQUESTED = typeof SUGGESTION_REQUESTED;

export const SUGGESTION_REQUEST_COMPLETED = "SUGGESTION_REQUEST_COMPLETED";
export type SUGGESTION_REQUEST_COMPLETED = typeof SUGGESTION_REQUEST_COMPLETED;

export const SUGGESTION_REQUEST_CANCELED = "SUGGESTION_REQUEST_CANCELED";
export type SUGGESTION_REQUEST_CANCELED = typeof SUGGESTION_REQUEST_CANCELED;

