export const INCREMENT_ENTHUSIASM = "INCREMENT_ENTHUSIASM";
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const INCREMENT_ENTHUSIASM_BY = "INCREMENT_ENTHUSIASM_BY";
export type INCREMENT_ENTHUSIASM_BY = typeof INCREMENT_ENTHUSIASM_BY;

export const DECREMENT_ENTHUSIASM = "DECREMENT_ENTHUSIASM";
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;
